name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "I have been triggered by a(n) ${{ github.event_name }} event."
      - name: Show the event payload
        run: |
          echo "The event payload is:"
          echo "${{ toJson(github.event) }}"
          