name: 04 - Using Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 0. Checkout the code from the repository
    # 1. Install dependencies of our React application
    # 2. Execute the automated tests
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Printing Folders
        run: |
          echo "Printing folder structure..."
          ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci

